### ISSUE TITLE
Image path within Sass file

### ISSUE THREAD

**Issue by njosefbeck** [dr-martin/jquery-fancybox#1]
Hello!

Maybe I'm missing something, but it seems that inside **jquery.fancybox.scss**, the references to images should be using the path **url('../img/img-name')** in order to properly load the images from the package's img directory. Is this how it should be?

When I currently use that sass file as is, I get a 404 error in the console, where the image files referenced in jquery.fancybox.scss are not found.

EDIT:
Actually, in thinking further about this, what would be nice is if there was a Sass variable with the image path, that we could then overwrite, to suit our own purposes when importing the file into our projects.

Something like:

``` scss
$image-path: '.../.../node_modules/img';
@import 'jquery.fancybox';
```

And then the jquery.fancybox.scss file would have the following at the top:

``` scss
$image-path: "../img" !default;
```

Thoughts?

**Comment by fractefactos** [comment]
Hi @njosefbeck,

This is because in the original structure project we want to get that image from a .css result file of .scss file, you use a preprocessor process like grunt or gulp? 
In that case you can generate the css result file in root directory and all will work fine!

**Comment by njosefbeck** [comment]
Yes, I use gulp and output my Sass file as CSS into its own directory. 

The issue is that the URL path for the images will still be relative to wherever I output that CSS file. I want to use the image files within your npm package, so I need a way to dynamically change the URL of the image path in order to target those image files based on my project's file structure. This is accomplished by setting a variable before I import the sass file into the Sass file where I import all of my other Sass files.

This is accomplished in the solution that I propose. Give me a moment and I'll have a pull request for you to check out, if you want to bring the solution into your project.

Also, let me know if you want me to explain this in greater detail!

**Comment by fractefactos** [comment]
Go ahead and we can take a look in your pull request.

**Comment by njosefbeck** [comment]
Great! Here it is: https://github.com/dr-martin/jquery-fancybox/pull/2
