### ISSUE TITLE
Update NPM package?

### ISSUE THREAD

**Issue by njosefbeck** [dr-martin/jquery-fancybox#3]
Hello,

Back in May you merged in my suggestion, which I greatly appreciated, but it seems like the version on NPM doesn't include my code. Is it possible for you to update that NPM package by chance? I would greatly appreciate it as I'm using this package in a current project.

Thanks!

**Comment by fractefactos** [comment]
Done!. Sorry for my late.

**Comment by njosefbeck** [comment]
Thanks!
